apply plugin: 'com.android.library'

android {
  namespace 'com.orhanobut.hawk'
  compileSdkVersion rootProject.ext.compileSdkVersion

  defaultConfig {
    minSdkVersion rootProject.ext.minSdkVersion
    consumerProguardFiles 'proguard-rules.pro'
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }

  compileOptions {
    sourceCompatibility rootProject.ext.sourceCompatibilityVersion
    targetCompatibility rootProject.ext.targetCompatibilityVersion
  }

  publishing {
    singleVariant('release') {
      withSourcesJar()
    }
  }

  testOptions {
    unitTests {
      includeAndroidResources true
    }
  }
}

dependencies {
  implementation deps.gson
  implementation deps.datastorePrefs
  implementation deps.coroutines
  implementation deps.kotlin

  testImplementation deps.junit
  testImplementation deps.truth
  testImplementation deps.robolectric
  testImplementation deps.mockito
  testImplementation deps.kotlin

  androidTestImplementation deps.junit
  androidTestImplementation deps.truth
  androidTestImplementation deps.espressoRunner
  androidTestImplementation deps.espressoRules
  androidTestImplementation deps.kotlin
}

apply from: rootProject.file('gradle/maven_push.gradle')
