apply plugin: 'com.android.application'

android {
  namespace 'com.orhanobut.hawk.sample'
  compileSdkVersion rootProject.ext.compileSdkVersion

  defaultConfig {
    applicationId "com.orhanobut.hawk.sample"
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
    versionCode 1
    versionName "3.0.0"
  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }

  compileOptions {
    sourceCompatibility rootProject.ext.sourceCompatibilityVersion
    targetCompatibility rootProject.ext.targetCompatibilityVersion
  }
}

dependencies {
  implementation 'androidx.appcompat:appcompat:1.7.0'
  implementation project(':hawk')
}
